version: '2'
services:
    web:
        build: app/
        ports:
            - "5000:5000"
        volumes:
            - .:/app
        depends_on:
            - redis
        command: flask run
    redis:
        image: redis