version: '2'
services:
    web:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - .:/.
        # depends_on:
            # - redis
        command: flask run
    # redis:
    #     image: redis